#!/bin/sh

mkdir ../bin
mkdir ../bin/mac64
mkdir ../export
mkdir ../export/scripts

cd hxml
haxe compile-mac64.hxml
cd ..

cp src/DefaultAssetLibrary.hx ../export
cp src/scripts/MyAssets.hx ../export/scripts
cp src/scripts/MyScripts.hx ../export/scripts

cp temp/mac64/StencylCppia ../bin/mac64